import logging
import time
import requests
from bs4 import BeautifulSoup

def standaard_scrape(task_id, start_date, end_date):
    """
    Scrapes the archive of the newspaper The Standaard
    http://www.standaard.be/zoeken?keyword=
    :param task_id: Task id generated by Celery
    :param start_date: The startDate of the search
    :param end_date: The end date of the search
    :return:
    """
    standaard_url = "http://www.standaard.be/zoeken?keyword="
    logger = logging.getLogger('newsscraper')
    r = requests.get(standaard_url)
    logger.debug("End of standaard scrape")
